### ISSUE TITLE
Unclear Documentation

### ISSUE THREAD

**Issue by joubin** [IngmarStein/SMJobKit#1]
Sorry if part of this question is due to my ignorance. 

But, here is what I have 

```
   var errors:NSError!

        do{
         try SampleService.installWithPrompt("some message")
        }catch {
            errors = error as NSError
        }

        if (errors != nil){
            print("Got an error")
        }else{
            print("all good")
        }

```

Here is sample service

```
import SMJobKit

class SampleService : Client{
//    let identifier =  "io.jabbari.Away.SampleService"

    override class var serviceIdentifier: String {
        return "io.jabbari.Away.SampleService"
    }
}
```
1. Why would one of the errors be bundleNotFound?
2. How can I fix that?
3. Now, I believe my SampleService is able to run in a higher privilege mode? 
4. Also, how can I retain that privilege escalation the next time the applications launches?

Once, I figure these out, I'd love to add to the read me about how I made my project. 

Here is the full project if you'd like to look at it: [project](https://github.com/joubin/away)
Thanks for the great work

**Comment by IngmarStein** [comment]
So, is this just a request for a better documentation or are you actually running into the bundleNotFound error?

bundleNotFound can be thrown if SMJobKit can't find the helper program in the following path: "(appBundle)/Contents/Library/LaunchServices/(serviceIdentifier)"

It can be fixed by moving the helper there. If everything is set up correctly, your helper will be run as a privileged process. The user only needs to provide the password for the installWithPrompt operation. For subsequent runs, you just connect to your already-installed helper.

**Comment by joubin** [comment]
@IngmarStein Thank you for wiring back. I was getting  the `bundleNotFound` error. But this morning, I fixed that problem. Now I'm getting `BadBundleCodeSigningDictionary`.

Are these specific errors from this lib, or a something that I can find documentation else where?
Thank you for your time. 

PS: I am writing new documentation as I go. I will do a merge request when I get it fully functional. 

Thanks

**Comment by IngmarStein** [comment]
BadBundleCodeSigningDictionary is thrown, if
- CFBundleVersion in your helper's info plist was not a string
- if your helper's info plist is not a dictionary
- if your helper's code signing dictionary could not be read

(see https://github.com/IngmarStein/SMJobKit/blob/master/SMJobKit/ClientUtility.swift)

**Comment by joubin** [comment]
@IngmarStein Thank you so much again for getting back to me. 

So, I found the problem by looking through all of the settings between the sample application and my applications. Seemed that `Other Linker Flags` was not set on the helper. However, after doing so, I get the following:

```
Got an error
Error Domain=SMJobKit.SMJError Code=4 "(null)"
Optional("6")
```

I know that 6 is my Bundle version, but not sure what `Error Domain=SMJobKit.SMJError Code=4 "(null)"` means.

The call for check problems like the one in the `SampleApplication` prints nothing:

```
  let version = SampleService.bundledVersion
 // let install = SampleService.installedVersion // This doesn't work; installedVersion doesn't exist
        print(version)
        for i in SampleService.checkForProblems(){
            print("problem")
            print(i)
        }
```

Here is the code that calls the SampleService

```
  func installService(){
        var errors:NSError!

        do{
         try SampleService.installWithPrompt("")
        }catch {
            errors = error as NSError
        }

        if (errors != nil){
            print("Got an error")
            self.appendMessage(errors.localizedDescription)
        }else{
            print("all good")

            self.appendMessage("Successfully installed SampleService")
        }

        self.updateStatus()
        SampleService.doSomething()

    }

```

I see that the error is being thrown at the `installWithPrompt` implementation on line 32 of Client.swift

Here is the code:

```
    public class func installWithPrompt(prompt:String?) throws {
        let authRef = try ClientUtility.authWithRight(kSMRightBlessPrivilegedHelper, prompt:prompt)

        // Here's the good stuff
        var cfError: Unmanaged<CFError>? = nil
        if !SMJobBless(kSMDomainSystemLaunchd, cfIdentifier, authRef, &cfError) {
            let blessError = cfError!.takeRetainedValue() as NSError
            throw SMJError.UnableToBless(blessError) // String(format: "SMJobBless failure (code %ld): %@", blessError.code, blessError.localizedDescription)
        }

        NSLog("%@ (%@) installed successfully", serviceIdentifier, bundledVersion!)
    }

```

Unsure what Im doing wrong

**Comment by IngmarStein** [comment]
SMJobBless can be a pain and sometimes hard to debug. You could try Apple's SMJobBlessUtil tool from the following sample code to locate the issue: https://developer.apple.com/library/mac/samplecode/SMJobBless/
You can use it as follows:

```
./SMJobBlessUtil.py check /path/to/your.app
```

**Comment by joubin** [comment]
Yeah, this totally is a pain. Apple should make it easier/clearer 

The utility printed many many many things and I'm finally stuck at this:

```
09:46:02 - joubin@data:[~/Downloads/SMJobBless]: ./SMJobBlessUtil.py check /Users/joubin/Desktop/Away\ 2016*/Products/Applications/Away.app
SMJobBlessUtil.py: tool designated requirement (identifier "io.jabbari.Away" and anchor apple generic and certificate leaf[subject.CN] = "Mac Developer: joubin jabbari (Z5Z9QY2N9P)" and certificate 1[field.1.2.840.113635.100.6.2.1] /* exists */) doesn't match entry in 'SMPrivilegedExecutables' (identifier SampleService and certificate leaf[subject.CN] = "Mac Developer: joubin jabbari (Z5Z9QY2N9P)")
```

Thank you so much for taking the time. Let me know what else I can do. Thank's @IngmarStein.

**Comment by IngmarStein** [comment]
I think you forgot to change SMPrivilegedExecutables in the Info.plist, it still contains the placeholder `identifier SampleService`.

**Comment by joubin** [comment]
No, I too named my service SampleService. Do you mind taking a look at my project? [`Here is my code`](https://github.com/joubin/away)

**Comment by IngmarStein** [comment]
The error message is pretty clear about the issue:
`Tool designated requirement (identifier "io.jabbari.Away" and anchor apple generic and certificate …)
doesn't match entry in 'SMPrivilegedExecutables' (identifier SampleService and certificate leaf[subject.CN] = "Mac Developer: joubin jabbari (Z5Z9QY2N9P)")`
means that the privileged tool uses a different identifier ("io.jabbari.Away") than what you specified in SMPrivilegedExecutables ("SampleService").

**Comment by joubin** [comment]
Thank you for all of the help @IngmarStein. 

I belive I have properly configured the plists. I basically took the one that comes with this application and did a search and replace with my apps names and certificates. But I understand that this question isn't really a problem with your lib any more.

For anyone else running into the above issue, I have posted the question [here on stackoverflow](http://stackoverflow.com/questions/34939243/gain-administration-privileges-with-swift-for-a-mac-application) and set a bounty. Hope it get's answered.
