### ISSUE TITLE
How to execute privileged exception

### ISSUE THREAD

**Issue by joubin** [IngmarStein/SMJobKit#2]
Can you provide an example how the application can call upon the helper to execute something with an recently gained privileges? 

**Running admin tasks**
[Apples Documentation ](https://developer.apple.com/library/mac/documentation/Security/Reference/authorization_ref/#//apple_ref/doc/constant_group/Authorization_Rights_Mask) requires the `authReferance` to be used. Is there  a way to get that from the client and pass it to the task. 

Put simply, can you add to the sample application a means of running a simple command that requires  admin privilege?

**Reconnecting to the helper**

In [another post](https://github.com/IngmarStein/SMJobKit/issues/1) @IngmarStein said 

> The user only needs to provide the password for the installWithPrompt operation. For subsequent runs, you just connect to your already-installed helper.

Could you also provide an example on how to reconnect to the helper after the computer has been rebooted and the application is being launched again.

Thank you

**Comment by IngmarStein** [comment]
I use SMJobKit in the following application: https://github.com/IngmarStein/Monolingual. I use XPC to communicate to the privileged helper (see https://github.com/IngmarStein/Monolingual/blob/master/XPCService/XPCService.swift). When you request a connection to the named service, the launchd locates the privileged helper and launches it. It's only if it hasn't been installed before, when you need the authorization from the user.

**Comment by joubin** [comment]
Thank you. This is perfect. Thank you for all of your help @IngmarStein.

I'm in the process of making a read me/tutorial. I can do a pull request when its done if you'd like
