### ISSUE TITLE
Sample Application does not build in current XCode (Version 7.3.1 (7D1014))

### ISSUE THREAD

**Issue by godzillabytes** [IngmarStein/SMJobKit#4]
I get the following errors:

SampleApplication/AppDelegate.swift:27:79: Extra argument 'error' in call

SampleApplication/AppDelegate.swift:41:7: Type 'SampleService' has no member 'uninstallWithPrompt'

SampleApplication/AppDelegate.swift:52:44: Type 'SampleService' has no member 'installedVersion'

SampleApplication/AppDelegate.swift:54:61: Value of type 'ErrorType' has no member 'description'

I can solve the first and the last one. But it looks like uninstallWithPrompt and installedVersion are missing in Client which is the Parent Class of SampleService. Or is there a different explanation?

**Comment by IngmarStein** [comment]
Thanks for reporting. The sample application has been outdated for a while and I just pushed an update to bring it up to date.

**Comment by IngmarStein** [comment]
Did the updated sample project help you? I wanted to add an explanation why the uninstall functionality has been removed: SMJobRemove had been deprecated and required a second authentication prompt. If you need to uninstall the helper, it should have the ability to do that by itself, e.g. with a command line switch or XPC message (which is outside the scope of the sample application). However, you can just install the new helper if you only want to update it, SMJobBless should handle this situation (barring a few bugs in macOS).
